// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

const String runtimeEventClearLogs = 'clearLogs';
const String runtimeEventClient = 'client';
const String runtimeEventGroups = 'groups';
const String runtimeEventLogLevel = 'logLevel';
const String runtimeEventLogs = 'logs';
const String runtimeEventNativeLog = 'nativeLog';
const String runtimeEventNetwork = 'network';
const String runtimeEventState = 'state';
const String runtimeEventStatus = 'status';
const String notificationTrafficModeSpeed = 'speed';
const String notificationTrafficModeTotal = 'total';
const String notificationTrafficModeBoth = 'both';

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class RuntimeFlagsMessage {
  RuntimeFlagsMessage({
    this.wakeLockEnabled,
    this.networkHeartbeatEnabled,
    this.networkHeartbeatIntervalSeconds,
    this.memoryLimitEnabled,
  });

  bool? wakeLockEnabled;

  bool? networkHeartbeatEnabled;

  int? networkHeartbeatIntervalSeconds;

  bool? memoryLimitEnabled;

  List<Object?> _toList() {
    return <Object?>[
      wakeLockEnabled,
      networkHeartbeatEnabled,
      networkHeartbeatIntervalSeconds,
      memoryLimitEnabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static RuntimeFlagsMessage decode(Object result) {
    result as List<Object?>;
    return RuntimeFlagsMessage(
      wakeLockEnabled: result[0] as bool?,
      networkHeartbeatEnabled: result[1] as bool?,
      networkHeartbeatIntervalSeconds: result[2] as int?,
      memoryLimitEnabled: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RuntimeFlagsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(wakeLockEnabled, other.wakeLockEnabled) && _deepEquals(networkHeartbeatEnabled, other.networkHeartbeatEnabled) && _deepEquals(networkHeartbeatIntervalSeconds, other.networkHeartbeatIntervalSeconds) && _deepEquals(memoryLimitEnabled, other.memoryLimitEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RuntimeFlagsMessage(wakeLockEnabled: $wakeLockEnabled, networkHeartbeatEnabled: $networkHeartbeatEnabled, networkHeartbeatIntervalSeconds: $networkHeartbeatIntervalSeconds, memoryLimitEnabled: $memoryLimitEnabled)';
  }
}

class NetworkInterfaceStateMessage {
  NetworkInterfaceStateMessage({
    required this.available,
    this.interfaceName,
    required this.interfaceIndex,
    required this.generation,
    this.reason,
    required this.updatedAtMillis,
  });

  bool available;

  String? interfaceName;

  int interfaceIndex;

  int generation;

  String? reason;

  int updatedAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      available,
      interfaceName,
      interfaceIndex,
      generation,
      reason,
      updatedAtMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static NetworkInterfaceStateMessage decode(Object result) {
    result as List<Object?>;
    return NetworkInterfaceStateMessage(
      available: result[0]! as bool,
      interfaceName: result[1] as String?,
      interfaceIndex: result[2]! as int,
      generation: result[3]! as int,
      reason: result[4] as String?,
      updatedAtMillis: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NetworkInterfaceStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) && _deepEquals(interfaceName, other.interfaceName) && _deepEquals(interfaceIndex, other.interfaceIndex) && _deepEquals(generation, other.generation) && _deepEquals(reason, other.reason) && _deepEquals(updatedAtMillis, other.updatedAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NetworkInterfaceStateMessage(available: $available, interfaceName: $interfaceName, interfaceIndex: $interfaceIndex, generation: $generation, reason: $reason, updatedAtMillis: $updatedAtMillis)';
  }
}

class UrlTestRequestMessage {
  UrlTestRequestMessage({
    required this.groupTag,
    required this.targetOutboundTag,
    required this.priorityOutboundTag,
    required this.excludeOutboundTag,
    required this.url,
    required this.timeoutMillis,
    required this.concurrency,
    required this.deadlineMillis,
    required this.force,
  });

  String groupTag;

  String targetOutboundTag;

  String priorityOutboundTag;

  String excludeOutboundTag;

  String url;

  int timeoutMillis;

  int concurrency;

  int deadlineMillis;

  bool force;

  List<Object?> _toList() {
    return <Object?>[
      groupTag,
      targetOutboundTag,
      priorityOutboundTag,
      excludeOutboundTag,
      url,
      timeoutMillis,
      concurrency,
      deadlineMillis,
      force,
    ];
  }

  Object encode() {
    return _toList();  }

  static UrlTestRequestMessage decode(Object result) {
    result as List<Object?>;
    return UrlTestRequestMessage(
      groupTag: result[0]! as String,
      targetOutboundTag: result[1]! as String,
      priorityOutboundTag: result[2]! as String,
      excludeOutboundTag: result[3]! as String,
      url: result[4]! as String,
      timeoutMillis: result[5]! as int,
      concurrency: result[6]! as int,
      deadlineMillis: result[7]! as int,
      force: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UrlTestRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(groupTag, other.groupTag) && _deepEquals(targetOutboundTag, other.targetOutboundTag) && _deepEquals(priorityOutboundTag, other.priorityOutboundTag) && _deepEquals(excludeOutboundTag, other.excludeOutboundTag) && _deepEquals(url, other.url) && _deepEquals(timeoutMillis, other.timeoutMillis) && _deepEquals(concurrency, other.concurrency) && _deepEquals(deadlineMillis, other.deadlineMillis) && _deepEquals(force, other.force);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UrlTestRequestMessage(groupTag: $groupTag, targetOutboundTag: $targetOutboundTag, priorityOutboundTag: $priorityOutboundTag, excludeOutboundTag: $excludeOutboundTag, url: $url, timeoutMillis: $timeoutMillis, concurrency: $concurrency, deadlineMillis: $deadlineMillis, force: $force)';
  }
}

class VpnNotificationPresentationMessage {
  VpnNotificationPresentationMessage({
    required this.detailed,
    required this.trafficDisplayMode,
    required this.trafficRefreshSeconds,
    required this.title,
    this.latencyMillis,
    required this.groupTag,
    required this.targetOutboundTag,
    required this.priorityOutboundTag,
    required this.excludeOutboundTag,
    required this.url,
    required this.timeoutMillis,
    required this.concurrency,
    required this.deadlineMillis,
    required this.connectedText,
    required this.checkingText,
    required this.unavailableText,
    required this.totalLabel,
    required this.refreshLabel,
    required this.stopLabel,
  });

  bool detailed;

  String trafficDisplayMode;

  int trafficRefreshSeconds;

  String title;

  int? latencyMillis;

  String groupTag;

  String targetOutboundTag;

  String priorityOutboundTag;

  String excludeOutboundTag;

  String url;

  int timeoutMillis;

  int concurrency;

  int deadlineMillis;

  String connectedText;

  String checkingText;

  String unavailableText;

  String totalLabel;

  String refreshLabel;

  String stopLabel;

  List<Object?> _toList() {
    return <Object?>[
      detailed,
      trafficDisplayMode,
      trafficRefreshSeconds,
      title,
      latencyMillis,
      groupTag,
      targetOutboundTag,
      priorityOutboundTag,
      excludeOutboundTag,
      url,
      timeoutMillis,
      concurrency,
      deadlineMillis,
      connectedText,
      checkingText,
      unavailableText,
      totalLabel,
      refreshLabel,
      stopLabel,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnNotificationPresentationMessage decode(Object result) {
    result as List<Object?>;
    return VpnNotificationPresentationMessage(
      detailed: result[0]! as bool,
      trafficDisplayMode: result[1]! as String,
      trafficRefreshSeconds: result[2]! as int,
      title: result[3]! as String,
      latencyMillis: result[4] as int?,
      groupTag: result[5]! as String,
      targetOutboundTag: result[6]! as String,
      priorityOutboundTag: result[7]! as String,
      excludeOutboundTag: result[8]! as String,
      url: result[9]! as String,
      timeoutMillis: result[10]! as int,
      concurrency: result[11]! as int,
      deadlineMillis: result[12]! as int,
      connectedText: result[13]! as String,
      checkingText: result[14]! as String,
      unavailableText: result[15]! as String,
      totalLabel: result[16]! as String,
      refreshLabel: result[17]! as String,
      stopLabel: result[18]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnNotificationPresentationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(detailed, other.detailed) && _deepEquals(trafficDisplayMode, other.trafficDisplayMode) && _deepEquals(trafficRefreshSeconds, other.trafficRefreshSeconds) && _deepEquals(title, other.title) && _deepEquals(latencyMillis, other.latencyMillis) && _deepEquals(groupTag, other.groupTag) && _deepEquals(targetOutboundTag, other.targetOutboundTag) && _deepEquals(priorityOutboundTag, other.priorityOutboundTag) && _deepEquals(excludeOutboundTag, other.excludeOutboundTag) && _deepEquals(url, other.url) && _deepEquals(timeoutMillis, other.timeoutMillis) && _deepEquals(concurrency, other.concurrency) && _deepEquals(deadlineMillis, other.deadlineMillis) && _deepEquals(connectedText, other.connectedText) && _deepEquals(checkingText, other.checkingText) && _deepEquals(unavailableText, other.unavailableText) && _deepEquals(totalLabel, other.totalLabel) && _deepEquals(refreshLabel, other.refreshLabel) && _deepEquals(stopLabel, other.stopLabel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnNotificationPresentationMessage(detailed: $detailed, trafficDisplayMode: $trafficDisplayMode, trafficRefreshSeconds: $trafficRefreshSeconds, title: $title, latencyMillis: $latencyMillis, groupTag: $groupTag, targetOutboundTag: $targetOutboundTag, priorityOutboundTag: $priorityOutboundTag, excludeOutboundTag: $excludeOutboundTag, url: $url, timeoutMillis: $timeoutMillis, concurrency: $concurrency, deadlineMillis: $deadlineMillis, connectedText: $connectedText, checkingText: $checkingText, unavailableText: $unavailableText, totalLabel: $totalLabel, refreshLabel: $refreshLabel, stopLabel: $stopLabel)';
  }
}

class HttpHeaderMessage {
  HttpHeaderMessage({
    required this.name,
    required this.value,
  });

  String name;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      name,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static HttpHeaderMessage decode(Object result) {
    result as List<Object?>;
    return HttpHeaderMessage(
      name: result[0]! as String,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HttpHeaderMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HttpHeaderMessage(name: $name, value: $value)';
  }
}

class UnderlyingNetworkFetchRequestMessage {
  UnderlyingNetworkFetchRequestMessage({
    required this.url,
    required this.headers,
    required this.maxBytes,
    required this.timeoutMillis,
  });

  String url;

  List<HttpHeaderMessage?> headers;

  int maxBytes;

  int timeoutMillis;

  List<Object?> _toList() {
    return <Object?>[
      url,
      headers,
      maxBytes,
      timeoutMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static UnderlyingNetworkFetchRequestMessage decode(Object result) {
    result as List<Object?>;
    return UnderlyingNetworkFetchRequestMessage(
      url: result[0]! as String,
      headers: (result[1]! as List<Object?>).cast<HttpHeaderMessage?>(),
      maxBytes: result[2]! as int,
      timeoutMillis: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnderlyingNetworkFetchRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) && _deepEquals(headers, other.headers) && _deepEquals(maxBytes, other.maxBytes) && _deepEquals(timeoutMillis, other.timeoutMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UnderlyingNetworkFetchRequestMessage(url: $url, headers: $headers, maxBytes: $maxBytes, timeoutMillis: $timeoutMillis)';
  }
}

class UnderlyingNetworkFetchResponseMessage {
  UnderlyingNetworkFetchResponseMessage({
    required this.statusCode,
    required this.body,
    required this.headers,
    required this.finalUrl,
    required this.network,
  });

  int statusCode;

  String body;

  List<HttpHeaderMessage?> headers;

  String finalUrl;

  String network;

  List<Object?> _toList() {
    return <Object?>[
      statusCode,
      body,
      headers,
      finalUrl,
      network,
    ];
  }

  Object encode() {
    return _toList();  }

  static UnderlyingNetworkFetchResponseMessage decode(Object result) {
    result as List<Object?>;
    return UnderlyingNetworkFetchResponseMessage(
      statusCode: result[0]! as int,
      body: result[1]! as String,
      headers: (result[2]! as List<Object?>).cast<HttpHeaderMessage?>(),
      finalUrl: result[3]! as String,
      network: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnderlyingNetworkFetchResponseMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(statusCode, other.statusCode) && _deepEquals(body, other.body) && _deepEquals(headers, other.headers) && _deepEquals(finalUrl, other.finalUrl) && _deepEquals(network, other.network);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UnderlyingNetworkFetchResponseMessage(statusCode: $statusCode, body: $body, headers: $headers, finalUrl: $finalUrl, network: $network)';
  }
}

class OutboundFetchRequestMessage {
  OutboundFetchRequestMessage({
    required this.outboundTag,
    required this.url,
    required this.headers,
    required this.maxBytes,
    required this.timeoutMillis,
  });

  String outboundTag;

  String url;

  List<HttpHeaderMessage?> headers;

  int maxBytes;

  int timeoutMillis;

  List<Object?> _toList() {
    return <Object?>[
      outboundTag,
      url,
      headers,
      maxBytes,
      timeoutMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static OutboundFetchRequestMessage decode(Object result) {
    result as List<Object?>;
    return OutboundFetchRequestMessage(
      outboundTag: result[0]! as String,
      url: result[1]! as String,
      headers: (result[2]! as List<Object?>).cast<HttpHeaderMessage?>(),
      maxBytes: result[3]! as int,
      timeoutMillis: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OutboundFetchRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outboundTag, other.outboundTag) && _deepEquals(url, other.url) && _deepEquals(headers, other.headers) && _deepEquals(maxBytes, other.maxBytes) && _deepEquals(timeoutMillis, other.timeoutMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OutboundFetchRequestMessage(outboundTag: $outboundTag, url: $url, headers: $headers, maxBytes: $maxBytes, timeoutMillis: $timeoutMillis)';
  }
}

class UnderlyingNetworkDownloadRequestMessage {
  UnderlyingNetworkDownloadRequestMessage({
    required this.url,
    required this.headers,
    required this.destinationPath,
    required this.maxBytes,
    required this.responseStartTimeoutMillis,
    required this.idleTimeoutMillis,
  });

  String url;

  List<HttpHeaderMessage?> headers;

  String destinationPath;

  int maxBytes;

  int responseStartTimeoutMillis;

  int idleTimeoutMillis;

  List<Object?> _toList() {
    return <Object?>[
      url,
      headers,
      destinationPath,
      maxBytes,
      responseStartTimeoutMillis,
      idleTimeoutMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static UnderlyingNetworkDownloadRequestMessage decode(Object result) {
    result as List<Object?>;
    return UnderlyingNetworkDownloadRequestMessage(
      url: result[0]! as String,
      headers: (result[1]! as List<Object?>).cast<HttpHeaderMessage?>(),
      destinationPath: result[2]! as String,
      maxBytes: result[3]! as int,
      responseStartTimeoutMillis: result[4]! as int,
      idleTimeoutMillis: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnderlyingNetworkDownloadRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) && _deepEquals(headers, other.headers) && _deepEquals(destinationPath, other.destinationPath) && _deepEquals(maxBytes, other.maxBytes) && _deepEquals(responseStartTimeoutMillis, other.responseStartTimeoutMillis) && _deepEquals(idleTimeoutMillis, other.idleTimeoutMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UnderlyingNetworkDownloadRequestMessage(url: $url, headers: $headers, destinationPath: $destinationPath, maxBytes: $maxBytes, responseStartTimeoutMillis: $responseStartTimeoutMillis, idleTimeoutMillis: $idleTimeoutMillis)';
  }
}

class UnderlyingNetworkDownloadResponseMessage {
  UnderlyingNetworkDownloadResponseMessage({
    required this.statusCode,
    required this.downloadedBytes,
    required this.headers,
    required this.finalUrl,
    required this.network,
  });

  int statusCode;

  int downloadedBytes;

  List<HttpHeaderMessage?> headers;

  String finalUrl;

  String network;

  List<Object?> _toList() {
    return <Object?>[
      statusCode,
      downloadedBytes,
      headers,
      finalUrl,
      network,
    ];
  }

  Object encode() {
    return _toList();  }

  static UnderlyingNetworkDownloadResponseMessage decode(Object result) {
    result as List<Object?>;
    return UnderlyingNetworkDownloadResponseMessage(
      statusCode: result[0]! as int,
      downloadedBytes: result[1]! as int,
      headers: (result[2]! as List<Object?>).cast<HttpHeaderMessage?>(),
      finalUrl: result[3]! as String,
      network: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnderlyingNetworkDownloadResponseMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(statusCode, other.statusCode) && _deepEquals(downloadedBytes, other.downloadedBytes) && _deepEquals(headers, other.headers) && _deepEquals(finalUrl, other.finalUrl) && _deepEquals(network, other.network);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UnderlyingNetworkDownloadResponseMessage(statusCode: $statusCode, downloadedBytes: $downloadedBytes, headers: $headers, finalUrl: $finalUrl, network: $network)';
  }
}

class ApkInspectionMessage {
  ApkInspectionMessage({
    required this.valid,
    required this.packageName,
    required this.installedPackageName,
    required this.versionName,
    required this.versionCode,
    required this.minSdk,
    required this.targetSdk,
    required this.deviceSdk,
    required this.signingCertificateSha256,
    required this.installedCertificateSha256,
  });

  bool valid;

  String packageName;

  String installedPackageName;

  String versionName;

  int versionCode;

  int minSdk;

  int targetSdk;

  int deviceSdk;

  List<String?> signingCertificateSha256;

  List<String?> installedCertificateSha256;

  List<Object?> _toList() {
    return <Object?>[
      valid,
      packageName,
      installedPackageName,
      versionName,
      versionCode,
      minSdk,
      targetSdk,
      deviceSdk,
      signingCertificateSha256,
      installedCertificateSha256,
    ];
  }

  Object encode() {
    return _toList();  }

  static ApkInspectionMessage decode(Object result) {
    result as List<Object?>;
    return ApkInspectionMessage(
      valid: result[0]! as bool,
      packageName: result[1]! as String,
      installedPackageName: result[2]! as String,
      versionName: result[3]! as String,
      versionCode: result[4]! as int,
      minSdk: result[5]! as int,
      targetSdk: result[6]! as int,
      deviceSdk: result[7]! as int,
      signingCertificateSha256: (result[8]! as List<Object?>).cast<String?>(),
      installedCertificateSha256: (result[9]! as List<Object?>).cast<String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApkInspectionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(valid, other.valid) && _deepEquals(packageName, other.packageName) && _deepEquals(installedPackageName, other.installedPackageName) && _deepEquals(versionName, other.versionName) && _deepEquals(versionCode, other.versionCode) && _deepEquals(minSdk, other.minSdk) && _deepEquals(targetSdk, other.targetSdk) && _deepEquals(deviceSdk, other.deviceSdk) && _deepEquals(signingCertificateSha256, other.signingCertificateSha256) && _deepEquals(installedCertificateSha256, other.installedCertificateSha256);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ApkInspectionMessage(valid: $valid, packageName: $packageName, installedPackageName: $installedPackageName, versionName: $versionName, versionCode: $versionCode, minSdk: $minSdk, targetSdk: $targetSdk, deviceSdk: $deviceSdk, signingCertificateSha256: $signingCertificateSha256, installedCertificateSha256: $installedCertificateSha256)';
  }
}

class InstalledAppMessage {
  InstalledAppMessage({
    required this.packageName,
    required this.label,
    required this.system,
    required this.launchable,
  });

  String packageName;

  String label;

  bool system;

  bool launchable;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      label,
      system,
      launchable,
    ];
  }

  Object encode() {
    return _toList();  }

  static InstalledAppMessage decode(Object result) {
    result as List<Object?>;
    return InstalledAppMessage(
      packageName: result[0]! as String,
      label: result[1]! as String,
      system: result[2]! as bool,
      launchable: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InstalledAppMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) && _deepEquals(label, other.label) && _deepEquals(system, other.system) && _deepEquals(launchable, other.launchable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InstalledAppMessage(packageName: $packageName, label: $label, system: $system, launchable: $launchable)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RuntimeFlagsMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NetworkInterfaceStateMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UrlTestRequestMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VpnNotificationPresentationMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is HttpHeaderMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is UnderlyingNetworkFetchRequestMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is UnderlyingNetworkFetchResponseMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is OutboundFetchRequestMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is UnderlyingNetworkDownloadRequestMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is UnderlyingNetworkDownloadResponseMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is ApkInspectionMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is InstalledAppMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return RuntimeFlagsMessage.decode(readValue(buffer)!);
      case 130:
        return NetworkInterfaceStateMessage.decode(readValue(buffer)!);
      case 131:
        return UrlTestRequestMessage.decode(readValue(buffer)!);
      case 132:
        return VpnNotificationPresentationMessage.decode(readValue(buffer)!);
      case 133:
        return HttpHeaderMessage.decode(readValue(buffer)!);
      case 134:
        return UnderlyingNetworkFetchRequestMessage.decode(readValue(buffer)!);
      case 135:
        return UnderlyingNetworkFetchResponseMessage.decode(readValue(buffer)!);
      case 136:
        return OutboundFetchRequestMessage.decode(readValue(buffer)!);
      case 137:
        return UnderlyingNetworkDownloadRequestMessage.decode(readValue(buffer)!);
      case 138:
        return UnderlyingNetworkDownloadResponseMessage.decode(readValue(buffer)!);
      case 139:
        return ApkInspectionMessage.decode(readValue(buffer)!);
      case 140:
        return InstalledAppMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SingboxHostApi {
  /// Constructor for [SingboxHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SingboxHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> prepareVpn(bool requiresVpn) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.prepareVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requiresVpn]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<Map<String?, Object?>> vpnPermissionStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.vpnPermissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<void> start(String config, bool useVpn) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config, useVpn]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startPrepared(bool useVpn) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.startPrepared$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[useVpn]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> applyConfig(String config, bool useVpn, bool restartCore) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.applyConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config, useVpn, restartCore]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> applyPreparedConfig(bool useVpn, bool restartCore) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.applyPreparedConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[useVpn, restartCore]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String> getConfigPath() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getConfigPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<Map<String?, Object?>> getRuntimeFlags() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getRuntimeFlags$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<void> setRuntimeFlags(RuntimeFlagsMessage flags) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.setRuntimeFlags$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[flags]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setRuntimeUiForeground(bool foreground) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.setRuntimeUiForeground$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[foreground]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> ensureNotificationPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.ensureNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> updateVpnNotificationPresentation(VpnNotificationPresentationMessage presentation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.updateVpnNotificationPresentation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[presentation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> reload() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.reload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stop(String reason) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[reason]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectOutbound(String groupTag, String outboundTag) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.selectOutbound$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[groupTag, outboundTag]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> urlTest(UrlTestRequestMessage request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.urlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<Map<String?, Object?>> status() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> lookupOutboundExternalInfo(String outboundTag) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.lookupOutboundExternalInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[outboundTag]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<NetworkInterfaceStateMessage> getNetworkInterfaceState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getNetworkInterfaceState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NetworkInterfaceStateMessage;
  }

  Future<String?> exportLogs(String content, String suggestedName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.exportLogs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[content, suggestedName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<bool> canInstallApks() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.canInstallApks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> openApkInstallSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.openApkInstallSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> installDownloadedApk() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.installDownloadedApk$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ApkInspectionMessage> inspectDownloadedApk(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.inspectDownloadedApk$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ApkInspectionMessage;
  }

  Future<Map<String?, Object?>> fetchUrlViaOutbound(OutboundFetchRequestMessage request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.fetchUrlViaOutbound$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<UnderlyingNetworkFetchResponseMessage> fetchUrlOnUnderlyingNetwork(UnderlyingNetworkFetchRequestMessage request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.fetchUrlOnUnderlyingNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as UnderlyingNetworkFetchResponseMessage;
  }

  Future<UnderlyingNetworkDownloadResponseMessage> downloadUrlOnUnderlyingNetwork(UnderlyingNetworkDownloadRequestMessage request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.downloadUrlOnUnderlyingNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as UnderlyingNetworkDownloadResponseMessage;
  }

  Future<List<String?>> resolveHostOnUnderlyingNetwork(String host) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.resolveHostOnUnderlyingNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[host]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String?>();
  }

  Future<String> getAndroidId() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getAndroidId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<Map<String?, Object?>> getSubscriptionRequestDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getSubscriptionRequestDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getPlatformDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getPlatformDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getAppVersionInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getAppVersionInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<String> getCoreVersion() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getCoreVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> getCoreCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getCoreCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> checkConfig(String config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.checkConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<Map<String?, Object?>> getPerformanceSnapshot() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getPerformanceSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<void> startRuntimeMeasurement(int durationSeconds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.startRuntimeMeasurement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[durationSeconds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopRuntimeMeasurement() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.stopRuntimeMeasurement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<Map<String?, Object?>> getRuntimeMeasurement() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getRuntimeMeasurement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<String> getRuntimeMeasurementReport() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getRuntimeMeasurementReport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<Map<String?, Object?>> getHappCrypt5Support() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getHappCrypt5Support$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  Future<List<InstalledAppMessage?>> getInstalledApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getInstalledApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<InstalledAppMessage?>();
  }

  Future<Uint8List?> getInstalledAppIcon(String packageName, int sizePx) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.getInstalledAppIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName, sizePx]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }

  Future<void> setQuickSettingsTileLabel(String label) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.meow_client.SingboxHostApi.setQuickSettingsTileLabel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[label]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
