import 'package:flutter/material.dart' as flutter;
import 'package:material_ui/material_ui.dart' as material_ui;

/// Converts the separate Material UI color scheme returned by dynamic_color
/// into the Flutter Material scheme used by the rest of the app.
flutter.ColorScheme toFlutterColorScheme(material_ui.ColorScheme source) {
  return flutter.ColorScheme(
    brightness: source.brightness,
    primary: source.primary,
    onPrimary: source.onPrimary,
    primaryContainer: source.primaryContainer,
    onPrimaryContainer: source.onPrimaryContainer,
    primaryFixed: source.primaryFixed,
    primaryFixedDim: source.primaryFixedDim,
    onPrimaryFixed: source.onPrimaryFixed,
    onPrimaryFixedVariant: source.onPrimaryFixedVariant,
    secondary: source.secondary,
    onSecondary: source.onSecondary,
    secondaryContainer: source.secondaryContainer,
    onSecondaryContainer: source.onSecondaryContainer,
    secondaryFixed: source.secondaryFixed,
    secondaryFixedDim: source.secondaryFixedDim,
    onSecondaryFixed: source.onSecondaryFixed,
    onSecondaryFixedVariant: source.onSecondaryFixedVariant,
    tertiary: source.tertiary,
    onTertiary: source.onTertiary,
    tertiaryContainer: source.tertiaryContainer,
    onTertiaryContainer: source.onTertiaryContainer,
    tertiaryFixed: source.tertiaryFixed,
    tertiaryFixedDim: source.tertiaryFixedDim,
    onTertiaryFixed: source.onTertiaryFixed,
    onTertiaryFixedVariant: source.onTertiaryFixedVariant,
    error: source.error,
    onError: source.onError,
    errorContainer: source.errorContainer,
    onErrorContainer: source.onErrorContainer,
    surface: source.surface,
    onSurface: source.onSurface,
    surfaceDim: source.surfaceDim,
    surfaceBright: source.surfaceBright,
    surfaceContainerLowest: source.surfaceContainerLowest,
    surfaceContainerLow: source.surfaceContainerLow,
    surfaceContainer: source.surfaceContainer,
    surfaceContainerHigh: source.surfaceContainerHigh,
    surfaceContainerHighest: source.surfaceContainerHighest,
    onSurfaceVariant: source.onSurfaceVariant,
    outline: source.outline,
    outlineVariant: source.outlineVariant,
    shadow: source.shadow,
    scrim: source.scrim,
    inverseSurface: source.inverseSurface,
    onInverseSurface: source.onInverseSurface,
    inversePrimary: source.inversePrimary,
    surfaceTint: source.surfaceTint,
  );
}
